name: Title Lint
slug: title-lint
type: meta
summary: Ensure all Pull Requests have the same title format.
subscribed_events:
  - pull_request.edited
  - pull_request.opened
  - pull_request.reopened
  - pull_request.synchronize
  - check_run.rerequested
