version: v2
name: Title Lint
slug: title-lint
type: content
summary: Check Pull Request Titles follow a standard convention.
beta: false
subscription_level: 0
default_configuration:
  installation:
    org: false
parameters:
  - name: regex
    description: Regular Expression to use to check Pull Request Titles
description: |
  This task is helpful if you want to ensure Pull Requests are linked
  with Ticketing Tools or you automatically generate release notes.
subscribed_events:
  - pull_request.edited
  - pull_request.opened
  - pull_request.reopened
  - pull_request.synchronize
  - check_run.rerequested
